.github/workflows/actions.yml

A GitHub secret token is no longer required to access the dell-csi-extensions repo
| #61  |
This is a GitHub Actions specific change. Nothing related to the karavi-resiliency source is changed.

Remove token usage

---

docs/INTEGRATION_TEST.md
internal/monitor/integration_steps_test.go

Update the integration tests to detect and work against Openshift clusters. A new environmental variable is required, which would have to point to the Bastion node. Test scripts will be first uploaded to the Bastion node, then to the individual Openshift nodes. Failure invocation is done from the Bastion node to the other Openshift nodes.
| #13 |
Ran the test pointing an Openshift cluster with the driver, resiliency enabled, and new env var set.
[openshift-test.log.txt](https://github.com/dell/karavi-resiliency/files/6307284/openshift-test.log.txt)
Ran Jenkins job that deploys upstream K8s and runs short integration test - Passed. https://__SIO3 Jenkins …

Openshift integration test

---

.github/containerscan/allowedlist.yaml
cmd/podmon/Dockerfile

A couple CVEs have been fixed, thus we should update the resiliency Docker image to use the latest packages that have the fixes.
| #66 |
Manually ran trivy against a local instance of the Docker image with the changes:
```console
[root@xxxx ~]# trivy image --severity HIGH,CRITICAL --exit-code 1 xxxxx:5000/podmon:v0.2.0x
2021-04-19T16:58:52.890-0400    INFO    Need to update DB
2021-04-19T16:58:52.890-0400    INFO    Downloading DB...
20.84 MiB / 20.84 MiB [---------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 10.03 MiB p/s 2s
2021-04-19T16:59:04.377-0400    INFO    Detecting RHEL/CentOS vulnerabilities... …
```

Update nettle and gnutls packages in resiliency image

---

internal/monitor/Makefile
internal/monitor/features/integration.feature
internal/monitor/features/node.feature
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
internal/monitor/short_integration_test.go

This refactors the integration test, which previously only ran for PowerFlex, to also support Unity with makefile targets powerflex-integration-test, unity-integration-test, powerflex-short-integration-test, unity-short-integration-test.
| |
- [x ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x ] I have not allowed coverage numbers to degenerate
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added tests that prove my fix is effective or that my feature works
* …

Unity integration test1

---

internal/monitor/features/integration.feature

For this PR we're removing a couple of extraneous cases for the unity-short-integration test, so that it is indeed short
| #13 |
TBA

Make unity-short-integration test even shorter

---

internal/monitor/features/integration.feature

Unity quick integration test is further streamlined, by removing the 'reboot' test cases.
| #22  |
Run internal Jenkins job to run tests against unity; was able to complete successfully.

Remove reboot test case for unity quick sanity.

---

internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go

This PR is an improvement for the e2e test. It will not validate that the pods that were failed over actually changed nodes. If not, the test will fail.
| #13 |
Ran the short-integration test locally.

Check for node change after a failure.

---

cmd/podmon/Dockerfile
cmd/podmon/main_test.go
internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
internal/monitor/monitor_test.go
internal/monitor/run.integration
internal/monitor/short_integration_test.go

Major changes are:
- Drop some test scenarios for Unity
- Enhance the SSH timeouts for the e2e test
- Change default godog test output to 'cucumber'
- Add unity integration test for the run.integration script
- Dockerfile update to address CVE-2021-33910
| #13  |
Running integration test

Post release work

---

cmd/podmon/Makefile

The docker build command in the Makefile should use the --no-cache option to make sure all the layers are rebuilt. This is to insure that the layer updating the dependencies gets rebuilt to pull the latest versions.
| #90  |
This is build related and no functional code has been updated.

Use --no-cache with docker build

---

test/podmontest/deploy/templates/test.yaml
test/podmontest/deploy/values-unity-nfs.yaml
test/podmontest/deploy/values-unity.yaml
test/podmontest/deploy/values-vxflex.yaml
test/podmontest/insu.sh
test/podmontest/insv.sh
test/podmontest/uns.sh
test/sh/nway.sh

This PR is primarily changes to the podmontest deployment script, to support node affinity show we can test volumes shared among multiple pods in deployment mode.
There are no go code changes. There are a couple of minor test script enhancements.
| |
- [x ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x ] I have not allowed coverage numbers to degenerate
- [x ] I have maintained at least 90% code coverage
- [x ] Run the podmontest helm chart in deployment and observe volumes are shared between multiple pods …

Changes for deployment node affinity sharing volumes

---

internal/monitor/features/integration.feature

Increase the failsecs time as kubernetes was slow to know the failure.
| #https://github.com/dell/csm/issues/199 |
4 scenarios (4 passed)
40 steps (40 passed)
51m0.450311685s
INFO[3065] Integration test finished
--- PASS: TestUnityShortIntegration (3060.46s)
PASS
status 0
ok      podmon/internal/monitor 3065.429s

Increase the failsecs time as kubernetes was slow to know the failure

---

.github/containerscan/allowedlist.yaml
internal/monitor/driver.go
internal/monitor/features/node.feature
internal/monitor/integration_steps_test.go
internal/monitor/monitor_steps_test.go
internal/utils/linuxLoopBackDevice.go
internal/utils/mock.go

Occasional failure unmounting Unity volume for raw block devices via iSCSI.
| #https://github.com/dell/csm/issues/237 |
time="2022-04-06T18:48:40Z" level=info msg="losetup output: /dev/loop2: [0005]:4601283 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/podmonvol-af77815a05/dev/584926b7-4368-4c26-9841-c56ca3b57267)\n"
time="2022-04-06T18:48:40Z" level=info msg="LOOOOOOOOOOOOOOOOPPPPBACK DEVICE: /dev/loop2"
time="2022-04-06T18:48:40Z" level=info msg="sucessfully unmounted block device: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/podmonvol-af77815a05/dev/584926 …

Occasional failure unmounting Unity volume for raw block devices via iSCSI

---

cmd/podmon/features/main.feature
cmd/podmon/main.go
internal/monitor/driver.go
internal/monitor/features/node.feature
internal/monitor/monitor_steps_test.go

| https://github.com/dell/csm/issues/262 |
Unit-test Output
PASS
coverage: 92.6% of statements
status 0
ok      podmon/internal/monitor 8.603s  coverage: 92.6% of statements

Added support for CSI-PowerScale

---

cmd/podmon/main.go
internal/k8sapi/mock.go
internal/monitor/controller.go
internal/monitor/features/controller.feature
internal/monitor/monitor.go
internal/monitor/monitor_steps_test.go
internal/monitor/node.go

The CSI node driver when not running on a WN (worker node). the CSI controller should check and taint that node so that pods are not scheduled on that node.
| #https://github.com/dell/csm/issues/145  |
time="2022-05-19T14:00:25-04:00" level=info msg="Node-mode test finished"
--- PASS: TestNodeMode (1.84s)
=== RUN   TestMapEqualsMap
--- PASS: TestMapEqualsMap (0.00s)
=== RUN   TestPowerFlexShortCheck
time="2022-05-19T14:00:25-04:00" level=info msg="Skipping short integration test. To enable short integration test: export RESILIENCY_SHORT_INT_TEST=true"
--- PASS: …

Protect CSI driver node pods to avoid storage workload scheduling

---

internal/monitor/Makefile
internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
internal/monitor/run.integration
internal/monitor/short_integration_test.go
test/podmontest/deploy/values-isilon.yaml
test/podmontest/insi.sh
test/sh/SCALE_TEST.md
test/sh/scaleup-powerscale.sh

This is PR is used for making the changes wrt to Integration and Scalability tests for csi-powerscale driver
|https://github.com/dell/csm/issues/262|
- Added Integration testcases for csi-powerscale and tested by executing each of them manually
Testcases performed:
| kubeConfig | podsPerNode | nVol  | nDev  | driverType | storageClass | workers     | primary | failure         | failSecs | deploySecs | runSecs | nodeCleanSecs |
| ""         | "1-2"       | "1-1" | "0-0" | "isilon"   | "isilon"     | "one-third" | "zero"  | "interfacedown" | 600      | 900        | 900     | 900 …

CSI-Powerscale resiliency integration & scalability tests

---

internal/monitor/Makefile
internal/monitor/run.integration

This PR is used for fixing the formatting issue in Makefile
| https://github.com/dell/csm/issues/262|
- [] I have made corresponding changes to the documentation

makefile formatting issue fixed

---

tools/monx.sh

Add support for --once so that monx.sh can be run only once
https://github.com/dell/csm/issues/262

add support for --once in monx.sh

---

internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go

The CSI node driver when not running on a WN (worker node). the CSI controller should check and taint that node so that pods are not scheduled on that node.
| #https://github.com/dell/csm/issues/145  |

Add integration test for CSI Driver node pod monitor

---

cmd/podmon/main.go

Resiliency Integration test fails when 2 drivers (csi-powerflex & csi-powerscale) installed on the same machine.
| #https://github.com/dell/csm/issues/325 |

Resiliency Integration fails on multiple drivers with driver pod monitor

---

cmd/podmon/Dockerfile

Updated the UBI for resiliency from 8.6-902 to 8.6-903.1661794351
| dell/csm#350|
- [✓ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ✓] Backward compatibility is not broken
[✓] powerflex-short-integration-test
[✓ ] powerflex-integration-test

Updated UBI image to 8.6-903.1661794351

---

internal/monitor/node.go

Sometimes get pvc call return error for pods that has pvc on it, making sure we do not ignore those pods in node cleanup process add err check.
| #https://github.com/dell/csm/issues/493 |

ignore pods with no pvcs

---

internal/monitor/integration_test.go
internal/monitor/short_integration_test.go

PowerScale Resiliency integration  output test results in XML format
| https://github.com/dell/csm/issues/859|
```
Examples:
| kubeConfig | podsPerNode | nVol  | nDev  | driverType | storageClass | workers     | primary | failure         | failSecs | deploySecs | runSecs | nodeCleanSecs |
| ""         | "1-1"       | "1-1" | "0-0" | "isilon"   | "isilon"     | "one-third" | "zero"  | "interfacedown" | 120      | 240        | 300     | 300           |
1 scenarios (1 passed)
10 steps (10 passed)
5m36.589770697s
INFO[0346] Integration test finished
--- PASS: …
```

Powerscale Resiliency Test Results in XML Format

---

.github/workflows/actions.yml
Makefile
README.md
cmd/podmon/Dockerfile
cmd/podmon/Makefile
scripts/buildubimicro.sh
test/podmontest/Makefile

Implementation of ubi-micro image for karavi-resiliency
| https://github.com/dell/csm/issues/922 |

Resiliency ubi-micro image 

---

cmd/podmon/Makefile

In the previous [PR ](https://github.com/dell/karavi-resiliency/pull/168) for Resiliency ubi-micro image update, there is a mistake on the image name when building the image which can cause publishing image fail. Fixed that error with right image name.
| https://github.com/dell/csm/issues/922|
Tested with automation on building and publishing the image.

Fix a small mistake on image name when building resiliency ubi-micro image

---

go.mod
go.sum

Updating karavi-resiliency gofsutil with the new release
|https://github.com/dell/csm/issues/885 |
Short integration test for powerflex
6 scenarios ([32m6 passed[0m)
60 steps ([32m60 passed[0m)
43m49.091590327s
time="2023-09-19T16:11:57-04:00" level=info msg="Integration test finished"
--- PASS: TestPowerFlexShortIntegration (2629.14s)
PASS
status 0
ok  	podmon/internal/monitor	2637.745s

Updating gofsutil version with latest release

---

.github/workflows/actions.yml
cmd/podmon/Makefile

Change the ubi-micro image version to 9.2 to always use the latest changes of 9.2 -- avoid minor patch updates. This change will remove CVE-2023-4911 observed in image scan.
|https://github.com/dell/csm/issues/843 |
Tested with automation in Jenkins.

Change ubi micro version to avoid vulnerability

---

internal/monitor/features/integration.feature

Increase powerflex e2e timeouts to account for any environment resource issues.
| #https://github.com/dell/csm/issues/1012 |

Increase the kubelet down test timeouts

---

.github/CODEOWNERS
go.mod
go.sum

Fix CVE by bumping up the library versions and update CODEOWNERS. 
|https://github.com/dell/csm/issues/1012|
- Unit test has passed locally
- Integration test has passed on Kubernetes 1.28 and Powerflex
```
27 scenarios ([32m27 passed[0m)
268 steps ([32m268 passed[0m)
3h4m21.647653133s
time="2023-11-06T14:36:45-05:00" level=info msg="Integration test finished"
--- PASS: TestPowerFlexIntegration (11061.68s)
PASS
status 0
ok  	podmon/internal/monitor	11081.981s
Resiliency test(s) passed
```

Fix CVE and update CODEOWNERS

---

.golangci.yaml
cmd/podmon/main.go
cmd/podmon/main_steps_test.go
internal/criapi/criapi.go
internal/criapi/criapi_test.go
internal/criapi/mock.go
internal/csiapi/mock.go
internal/k8sapi/interface.go
internal/k8sapi/mock.go
internal/monitor/controller.go
internal/monitor/driver.go
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
internal/monitor/monitor.go
internal/monitor/monitor_steps_test.go
internal/monitor/node.go
internal/utils/linuxLoopBackDevice.go
internal/utils/mock.go
test/podmontest/podmontest.go
test/ssh/cli/main.go
test/ssh/client.go
test/ssh/client_test.go

- Fix format and linting issues
- Added skip dirs for go mod libraries (third party libraries)
- Change `ssh.InsecureIgnoreHostKey()` callback to a hostkey implementation that accepts empty string and emits a warning message of hostkey
|https://github.com/dell/csm/issues/926 |
- Unit test
- e2e integration test

Fix linting issue

---

.github/workflows/actions.yml
.github/workflows/linters.yaml
Dockerfile
Makefile
README.md
cmd/podmon/Dockerfile
cmd/podmon/Makefile

Implement docker multi stage build to build module and use common Go image for building module.
| https://github.com/dell/csm/issues/1098 |

Implement docker multi stage build and use common Go image

---

internal/monitor/controller.go
internal/monitor/features/controller.feature

Add error log and abort pod cleanup k8s event for missing CSI Annotations and volume host connectivity validation failure.
| https://github.com/dell/csm/issues/1216 |

Add error log and abort pod cleanup k8s event in controllerCleanupPod

---

go.mod
go.sum

Updated gofsutil dependency to the latest version 1.16.1.
| https://github.com/dell/csm/issues/1221 |
```
babija-dev:~/csm # git clone -b usr/babija/gofsutil-update https://github.com/dell/karavi-resiliency.git
Cloning into 'karavi-resiliency'...
remote: Enumerating objects: 1862, done.
remote: Counting objects: 100% (1084/1084), done.
remote: Compressing objects: 100% (591/591), done.
remote: Total 1862 (delta 764), reused 632 (delta 474), pack-reused 778
Receiving objects: 100% (1862/1862), 1.81 MiB | 7.96 MiB/s, done.
Resolving deltas: 100% (1120/1120), done.
babija-dev:~/csm # …
```

Updated gofsutil dependency to the latest version 1.16.1.

---

Makefile
core/.gitignore
core/core.go
core/semver.tpl
core/semver/semver.go
core/semver/semver_test.go
docker.mk

Added support for semver.go
Set image VERSION through semver.mk and removed the unnecessary hardcoded fields
| https://github.com/dell/csm/issues/1490 |
```
[root@lglw3182 karavi-resiliency]# make podman
curl -O -L https://raw.githubusercontent.com/dell/csm/main/config/csm-common.mk
...
go run core/semver/semver.go -f mk >semver.mk
make -f docker.mk podman DEFAULT_GOIMAGE=golang:1.23 CSM_BASEIMAGE=quay.io/dell/container-storage-modules/csm-base-image:nightly
make[1]: Entering directory '/root/riya/image_version_test/karavi-resiliency'
MAJOR 1 MINOR 12 PATCH 0 RELNOTE  SEMVER …
```

Ensure image version consistency

---

Makefile

This PR adds Makefile targets to run GitHub Actions checks locally:
`actions` Target :
Runs all pull request checks with enhanced logging.
`action-help` Target :
Displays instructions for running specific workflows with act.
Usage:
Run all PR checks: `make actions`
Get workflow instructions: `make action-help`
Enhances local testing and debugging of GitHub Actions.
| https://github.com/dell/csm/issues/1490|

karavi-resiliency/Add Makefile Targets for Local PR Checks

---

go.mod
internal/monitor/features/integration.feature
test/podmontest/insi.sh
test/podmontest/inspm.sh
test/podmontest/insps.sh
test/podmontest/insu.sh
test/podmontest/insv.sh

- Used nvme for PowerStore as the default, which is the protocol supported by nightly qualification currently.
- Cherry-picked podmantest image registry updates from https://github.com/dell/karavi-resiliency/compare/main...usr/evgeny/test-image-registry.
- Increased the timeout for the test case `Basic node failover testing using test StatefulSet pods (node interface down)` for PowerStore. It was observed in OCP environment that the timeout was too early.
| N/A |
```bash
4 scenarios ([32m4 passed[0m)
38 steps ([32m38 passed[0m)
40m31.036453982s
time="2025-03-07T12:25:52-05:00" …
```

Add Changes for Nightly Qualification

---

internal/monitor/features/integration.feature

PR changes the kubeletdown scenario for powermax integration test. In case of iscsi at least one device is required to run properly. Modifying number of devices 0 --> 1 helped to pass the test. 5/5 runs in a row passed on a k8s cluster. Also, on OCP cluster the short integration test passed as well 2 runs in a row.
|https://github.com/dell/csm/issues/1848|
[pmax-short-result_ocp.txt](https://github.com/user-attachments/files/19763033/pmax-short-result_ocp.txt)

Fix PowerMax integration test

---

internal/monitor/Makefile
internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
test/podmontest/deploy/templates/test.yaml
test/podmontest/deploy/values-powerstore-iscsi.yaml
test/podmontest/deploy/values-powerstore-nfs.yaml
test/podmontest/deploy/values-powerstore-nvme.yaml
test/podmontest/insps.sh

Add a new scenario that fails node which are labeled as preferred site to test metro with Resiliency.
| https://github.com/dell/csm/issues/1961|
Unit test:
```
make unit-test:
PASS
coverage: 96.8% of statements
status 0
ok      podmon/cmd/podmon       1.578s  coverage: 96.8% of statements
make[1]: Leaving directory '/root/workspace/karavi-resiliency/cmd/podmon'
```
Integration test:
```
time="2025-08-06T21:10:01+01:00" level=info msg="k8sPoll: Node: worker-2-rjcs0evho6ev5.domain Ready:true Taints: "
Given a kubernetes <kubeConfig> …
```

Add Preferred-site node failure scenario for metro resiliency

---

internal/monitor/features/virtualization.feature
internal/monitor/integration_steps_test.go

Add retry mechanism to VM read and write operation 
| https://github.com/dell/csm/issues/1896 |
```
RESILIENCY_VM_INT_TEST="true" \
RESILIENCY_TEST_CLEANUP="true" \
POLL_K8S="true" \
SCRIPTS_DIR="../../test/sh" \
go test -timeout 6h -test.v -test.run "^\QTestOcpVirtPowerFlexCheck\E|\QTestOcpVirtPowerFlexIntegration\E"
=== RUN   TestOcpVirtPowerFlexCheck
Feature: Virtual Machine Integration Test
As a CSM for Resiliency developer
I want to test OpenShift Virtualization with CSM for Resiliency in a OpenShift environment
So that it is known to work on various vm clean up cases and give …
```

Add retry mechanism to VM read and write operation 

---

internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go

The added scenario deploys test pod on preferred node and brings down the non-preferred node and verifies that pod is still running.
| |
Given a kubernetes <kubeConfig>                                                                                                                       
And cluster is clean of test pods                                                                                                                      
And wait <nodeCleanSecs> to see there are no taints                                                                                   
And label …

IntTest :non-preferred worker node down

---

internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go

It was identified that the labels for controller pods can be different between different drivers. This causes an issue when determining the controller pod for the driver.
For this reason, we changed the way in which the controller pod is identified because we can guarantee that it will always contain `<driverType>-controller`.
| |
```
2 scenarios (2 passed)
20 steps (20 passed)
16m39.338139204s
INFO[1059] Integration test finished
--- PASS: TestPowerScaleIntegration (999.35s)
PASS
status 0
ok      podmon/internal/monitor 1059.053
```
```
Given a kubernetes <kubeConfig> …
```

Fix: Driver Controller Pod Determination
