.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
ADOPTERS.md
README.md
docs/APPLICATIONS.md
docs/DEPLOYING.md
docs/DESIGN.md
docs/GETTING_STARTED_GUIDE.md
docs/INTEGRATION_TEST.md
docs/ISSUE_TRIAGE.md
docs/LIMITATIONS.md
docs/PROBLEMS.md
docs/RECOVERY.md
docs/SUPPORTED_DRIVERS.md
docs/TESTING.md
docs/USE_CASES.md
docs/VERSIONING.md
internal/monitor/features/integration.feature

Update the documentation to reflect the new naming of the product under the Container Storage Modules (CSM) umbrella. 
There were also few typos and grammatical updates included with the changes.
| #46 |
Documentation updates only.

Change Karavi references to CSM.

---

.github/containerscan/allowedlist.yaml
docs/DEPLOYING.md
docs/LIMITATIONS.md
docs/SUPPORTED_DRIVERS.md
test/sh/SCALE_TEST.md

This PR is for adding documentation covering support for resiliency with csi-unity drivers.
| #46 |
Documentation change.

Unity support documentation updates.

---

cmd/podmon/Dockerfile

Added label to Dockerfile to align with Dell EMC CSI Drivers
List the issues impacted by this PR:
| Issue ID |
| -------- |
|          |

Added label to Dockerfile

---

go.mod
go.sum

Update to use the latest released dell-csi-extension podmon release which has updated grpc dependencies
| |

Updated podmon extensions

---

.github/pull_request_template.md

Added checklist item to PR template to ensure backward compatibility is not broken
| N/A |
N/A

Added checklist item to PR template

---

internal/monitor/features/integration.feature
internal/monitor/integration_steps_test.go

add kubelet down integration test

---

cmd/podmon/Dockerfile

Upgrade ubi base image to 8.5-226.1645809065
| #https://github.com/dell/csm/issues/183 |

Upgrade ubi base image to 8.5-226.1645809065

---

go.mod
go.sum

upgrade gofsutil to latest release v1.8.0
| |

upgrade gofsutil to latest release v1.8.0

---

.github/containerscan/allowedlist.yaml

Update allow cve list with not yet fix new cve
| |

Update allow cve list with not yet fix new cve

---

README.md
cmd/podmon/main_test.go
internal/monitor/integration_test.go
internal/monitor/monitor_test.go
internal/monitor/short_integration_test.go

This PR adds Junit XML reports to godog test suites for qTest integration.
|https://github.com/dell/csm/issues/240 |

Add Junit XML reports for qTest integration

---

cmd/podmon/Dockerfile
go.mod
go.sum
internal/monitor/integration_steps_test.go

Upgrade ubi images and gofsutils
| #https://github.com/dell/csm/issues/243 |

Upgrade ubi images and gofsutils

---

cmd/podmon/Dockerfile

Updated the UBI for resiliency from 8.6-754 to 8.6-902 
|      dell/CSM#350       |
- [ ✓] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [✓ ] Backward compatibility is not broken
- [✓] Test : powerflex-short-integration-test

Updated UBI to 8.6-902

---

README.md

Updated link to adopters to point to correct location in github.com/dell/csm
| N/A |
I have verified the document update and ensured there are no broken links

Updated adopters link

---

go.mod
go.sum

Updated applicable goclients for Resiliency (gofsutil and dell-csi-extensions) to latest commit IDs
|dell/csm#491 |
27 scenarios (27 passed)
268 steps (268 passed)
3h1m49.481100602s
INFO[10973] Integration test finished                    
--- PASS: TestPowerFlexIntegration (10909.51s)
PASS
status 0
ok      podmon/internal/monitor 10973.292s

updated gomod dependencies

---

.github/containerscan/allowedlist.yaml
cmd/podmon/Dockerfile

Upgrade ubi imagefor fixes to CVEs
#| GitHub Issue # |
| #https://github.com/dell/csm/issues/545 |
27 scenarios (27 passed)
268 steps (268 passed)
2h54m8.33799514s
time="2022-11-16T15:29:28-05:00" level=info msg="Integration test finished"
--- PASS: TestPowerFlexIntegration (10448.37s)
PASS
status 0
ok      podmon/internal/monitor 10459.182s

Upgrade ubi imagefor fixes to CVEs

---

go.mod
go.sum

Update gofsutil library to the latest
| https://github.com/dell/csm/issues/491|
PowerFlex short integration
60 steps (60 passed)
40m30.9977938s
INFO[2441] Integration test finished
--- PASS: TestPowerFlexShortIntegration (2431.01s)
PASS
status 0
ok      podmon/internal/monitor 2441.617s
PowerFlex integration
268 steps (268 passed)
2h55m9.074305962s
time="2022-11-30T12:43:06-05:00" level=info msg="Integration test finished"
--- PASS: TestPowerFlexIntegration (10509.09s)
PASS
status 0
ok      podmon/internal/monitor 10519.646s

Update goclient library

---

.github/containerscan/allowedlist.yaml
cmd/podmon/Dockerfile

Update UBI image to address CVE's
|https://github.com/dell/csm/issues/612 |
6 scenarios ([32m6 passed[0m)
60 steps ([32m60 passed[0m)
40m37.527648545s
time="2023-01-12T21:12:43Z" level=info msg="Integration test finished"
--- PASS: TestPowerFlexShortIntegration (2437.55s)
PASS
status 0
ok  	podmon/internal/monitor	2448.447s

Update UBI image

---

.github/containerscan/allowedlist.yaml
cmd/podmon/features/main.feature
cmd/podmon/main.go
internal/monitor/driver.go
internal/monitor/features/node.feature
internal/monitor/monitor_steps_test.go

Added support for csi-powerstore driver
| https://github.com/dell/csm/issues/587 |

Add support for CSI-PowerStore

---

internal/monitor/Makefile
internal/monitor/features/integration.feature
internal/monitor/features/node.feature
internal/monitor/integration_steps_test.go
internal/monitor/integration_test.go
internal/monitor/monitor_steps_test.go
internal/monitor/run.integration
internal/monitor/short_integration_test.go
test/podmontest/deploy/values-powerstore-iscsi.yaml
test/podmontest/deploy/values-powerstore-nfs.yaml
test/podmontest/deploy/values-powerstore-nvme.yaml
test/podmontest/insps.sh
test/sh/SCALE_TEST.md
test/sh/scaleup-powerstore.sh

This PR is for making the changes wrt to Integration and Scalability tests for csi-powerstore driver
| https://github.com/dell/csm/issues/587 |
-----------------
------------------

CSI-PowerStore Resiliency Integration & Scalability Tests

---

internal/monitor/features/integration.feature

Add additional tests for short-integration test for PowerScale.
| #https://github.com/dell/csm/issues/583 |
5 scenarios (5 passed)
50 steps (50 passed)
49m53.403557026s
INFO[3003] Integration test finished
--- PASS: TestPowerScaleShortIntegration (2993.42s)
PASS
status 0
ok      podmon/internal/monitor 3003.104s

Add additional integration test for short-integration

---

.github/workflows/actions.yml
cmd/podmon/Dockerfile
internal/monitor/features/controller.feature
internal/monitor/run.integration
tools/collect_logs.sh

- Add race-detector parameter to unit test action 
- Update actions/checkout to v3 and actions/setup-go to v4
- Clean up of integration test where date was being returned twice and the driver namespace wasn't being returned at all in echo statement
| https://github.com/dell/csm/issues/733|

Github action enhancement

---

internal/monitor/integration_steps_test.go

CSM for Resiliency openshift test required to pass ssh options in scp command
| #https://github.com/dell/csm/issues/737 |

CSM for Resiliency openshift test required to pass ssh options in scp command

---

.github/containerscan/allowedlist.yaml
cmd/podmon/Dockerfile

PR to update UBI image to latest available.
| https://github.com/dell/csm/issues/843|
```
27 scenarios ([32m27 passed[0m)
268 steps ([32m268 passed[0m)
2h59m14.563130251s
time="2023-06-02T17:21:56Z" level=info msg="Integration test finished"
--- PASS: TestPowerFlexIntegration (10754.59s)
PASS
status 0
ok  	podmon/internal/monitor	10762.499s
```

UBI image update

---

.github/workflows/actions.yml
cmd/podmon/Makefile

Use common base image
| https://github.com/dell/csm/issues/1031 |

Use common base image

---

scripts/buildubimicro.sh

Update buildubimicro.sh repos

---

internal/monitor/monitor_steps_test.go
internal/monitor/monitor_test.go

Add additional check for pod and node watcher unit test.
| #https://github.com/dell/csm/issues/1098 |

Add additional check for pod and node watcher unit test

---

.github/CODEOWNERS
.github/workflows/actions.yml
go.mod
go.sum

Update storage clients to latest release.
|https://github.com/dell/csm/issues/1091 |
PASS
coverage: 96.8% of statements
status 0
ok      podmon/cmd/podmon       2.166s  coverage: 96.8% of statements

Update storage clients

---

Dockerfile
Makefile

Version bump up
|https://github.com/dell/csm/issues/1221|

Version bump up

---

scripts/buildubimicro.sh

This PR updates the UBI micro dependencies.
| https://github.com/dell/csm/issues/1221 |

Updating dependencies to UBI micro image.

---

Dockerfile
licenses/LICENSE

| https://github.com/dell/csm/issues/1221 |

Adding license to fix Preflight Checks failures

---

go.mod
go.sum

Update client libraries
|https://github.com/dell/csm/issues/1435 |

updated podmon to v1.6.0 and gofsutil to v1.17.0

---

.github/workflows/image-version-update.yaml

Changes for Image version update release action
| https://github.com/dell/csm/issues/1490 |

image version update release action

---

.github/workflows/release.yaml

Added fix for patch release (n-1)
|https://github.com/dell/csm/issues/1490 |
Tested for driver with fork (normal release): https://github.com/harishp8889/test-powerstore-automation/actions/runs/14374648455/job/40304179725

Added fix for patch release

---

internal/monitor/features/integration.feature

E2E Test for powerscale was failing with error:
```
time="2025-05-02T10:32:09-05:00" level=info msg="Done checking if all nodes are ready after 15m0.004054059s"
| [31m""[0m         | [31m"1-2"[0m       | [31m"2-2"[0m | [31m"0-0"[0m | [31m"isilon"[0m   | [31m"isilon"[0m     | [31m"one-third"[0m | [31m"zero"[0m  | [31m"reboot"[0m | [31m600[0m      | [31m900[0m        | [31m900[0m     | [31m900[0m           |
[1;31m
Error Trace:	/****/karavi-resiliency/internal/monitor/monitor_test_helpers.go:29
/****/karavi-resiliency/internal/monitor/integration_steps_test.go:1478
/****/karavi-resiliency/internal/monitor/integration_steps_test.go:543
/usr/local/go/src/reflect/value.go:584
/usr/local/go/src/reflect/value.go:368
/go/pkg/mod/github.com/cucumber/godog@v0.15.0/internal/models/stepdef.go:189 …
```

Increase timeout for Resiliency test for Powerscale

---

internal/monitor/features/integration.feature

Updated e2e with additional timeouts for the short integration tests
| |

Integration tests updates
